= OpenCPN JavaScripts library

This library shares scripts you can use as-is, or modify for your own needs.

[cols="1,1,2,1"] 
|===
|Name |Description |Details/instructions |Author

|link:https:../Driver/Driver.js[Driver.js]
|A simple way of driving the ship on a compass course or relative to a simulated wind.
|link:https:../Driver/Driver.adoc[instructions]
|Antipole

|link:https:../TackAdvisor/TackAdvisor.js[TackAdvisor.js]
|When close-hauled or running, displays suggested tacks
|link:https:../TackAdvisor/TackAdvisor.adoc[Instructions]
|Antipole

|link:https:../BuildRaceCourses/BuildRaceCourses.js[BuildRaceCourses.js]
|Build a race course from set of race marks
|link:https:../BuildRaceCourses/BuildRaceCourses.pdf[Instructions]
|Antipole
|===

=== Contributing to this library +
If you have developed a script that you would like to contribute, please store it somewhere online and send me

* the link to your script
* the description for the table entry
* the link to the instructions file if any

You could store your scripts and any descriptions as gists on GitHub.
This has the advantage of having version control if you modify it.

I keep my published scripts in a GitHub repository synchronised to a folder on my computer using GitHub Desktop.
They are thus available to me when offline afloat.  I can synchronise any modifications I might make back to the published version.
