= MessageNMEAsampling

https://github.com/antipole2/JavaScripts-shared/blob/main/MessageNMEAsampling.js[MessageNMEAsampling.js]

The OpenCPN Debugger plugin can be used to monitor NMEA sentences but the output can be difficult to use.
This script is an alternative.
It monitors OpenCPN messages and NMEA sentences over 30 seconds (configurable).

It then reports:

* which OpenCPN messages have been seen.
* which NMEA sentences have been seen and the count of each, sorted by type and then sender.
* for each NMEA sentence type and sender, it then lists one sample of each.

You might find one sample of each insufficient.  For example, you could have more than one sender using the same talker ID.
The script contains an array of sentence types which are to all be be displayed.
For example, configuring

`var displayThese = ["GPGGA", "JSVTG"];`

will cause all sentences of these types to be displayed in addition to the single samples.
To supress this feature, leave the array empty or set it to some non-existant type.
