= Boundaries Utility

https://github.com/antipole2/JavaScripts-shared/blob/main/Boundaries/boundary.js[boundary.js]

This utility allows selection and manipulation of waypoints, routes and tracks according to whether they ar inside a chosen boundary.

You create one or more boundaries using pseudo routes on OpenCPN.  A boundary must include the text 'boundary' in its name (case insensitive) and must share the first and last points.  If you have several boundaries, they may share routepoint borders.

The script searches for boundaries and displays a dialogue, such as this example:


It is an alternative to the ShipDriver plugin but does not use steering to gradually change course.

It generates GLL, VTG and WML NMEA sentences.  You could add others as required.

You can set Speed Over Ground (SOG), Course Over Ground (COG), Wind angle and wind speed.

Selecting *Compass course* will then drive the boat along the selected course.  The angle to the wind is displayed.
Alternatively, you can instead specify an angle to the wind and select *Port tack* or *Starboard tack*.  It will then calculate the required COG.
Selecting the opposite tack will tack the boat.

After changing the parameters, you need to click on one of the buttons to put the chnages into effect. 

TIP: Driver can be run in its own console and used, for example, to experiment with or test the TackAdvisor and SendActiveRoute scripts running in their own consoles.
