= Technical guide for the Housekeeper script

As this script is quite complex, this guid documents the script's structure and how it works.
It would be wise to read this before attempting to modify or maintain the Housekeepper script.

There are two variables set up early on which are useful during debugging.

`var log = false;`

If this is set to true, the script prints its progress and also certain structures developed during the analysis.

`var doSaves = true;`

If this is set to false, the changes are not actually saved back int OpenCPN even though they are reported.
THis allows testing without the inconvenience of having to restore the OpenCPN data to its previous state.

== Overall approach

The script uses internal JavaScript structures right up until the point where these are saved back into OpenCPN.
It has thus been possible to develop the script over several weeks without changing any data in OpenCPN.
The actual update phase is very simple and took only a couple of hours to implement and test.

|===
|Function|Purpose

|`load()`|Loads the waypoints and routes into JavaScript structures.
|`analyse()`|Analyses the structures and creates structures recording the issues found
|`report()`|Prints a report of the issues found and returns the number of issues
|`WhatToDoA()`|Presents the dialogue through which the user decides on actions relating to waypoints and routes
|`WhatToDoB()`|Presents a series of dialogues hrough which the user decides on actions relating to each location at which there are multiple points.
|`doSave()`|Saves the structures back into OpenCPN, thus implementing the changes.
|===

An advantage of implementing the phases as functions is that they can be repeated if need be.
For example, if points are removed from a route, that invalidates the indexing created by the analysis.
The analysis can be redone to update the indexing.

=== `load()`

This reads all waypoints and routes into the standard structures created by the JavaScript plugin.
It adds an `action` attribute and sets it to the custom symbol `none`.
During the changes, the action may be set to `remove` or `update` to indicate what action is required of doSave().

Each structure is pushed into an array of structures of `allpoints[]` and `routes[]`.

=== `analyse()`

Both `allpoints[]` and `routes[]` are sorted on their names.
This allows identification of unnamed and duplicate names.

A point is referenced by its index number in the allpoints array.
A leg within a route is identified by the index within the routes array and the leg number within that route.

For unnamed entries it is sufficient to build an array of these indexes.

For duplicates, we build a cluster of indexes for a given name and push the cluster onto the array.
Clusters may contain additional attributes noted during building.

The routepoints are scanned and clusters of successive repeated routepoints built.

Each point is given an exra attribute of 'uses[]', each use identifying the route index and leg number of that use.
The length of the uses array gives the number of times that point has been included in a route.
A length greater than 1 indicates the point is being shared.

To identify multiple points at or near the same location, we build a `location` structure.
Each location contains its position and an array of the marks.
To make matters simpler later, it also contains an array of the true ayiit names and their indexes.

Any location with only a single mark can then be thinned out.

Each location is then classified according to what it contains.
The classifications are defined in the `classifications` structure.

The locations are then sorred on classification so that subsequent processing is done class by class.

=== `report()`

The report is produced strictly from the structures build during the analysis.
This discipline ensures that all information need is hel within the structures.

=== `WhatToDoA()`

This function examines the structures and presents a dialogue with buttons for each kind of action for which there is an issue.

Processing of buttons has to be handled in a separate function and 

Function 'doNaming()' identifies the button selected and makes the required changes.
Each issue is shifted off the array of issues do that, when the dialogue is next presented, only buttons for remaining isues are displayed.
