descriptor129541 = {"PGN":129541,
        "Id":"gpsAlmanacData",
        "Description":"GPS Almanac Data",
        "Type":"Fast",
        "Complete":false,
        "Missing":[
          "Fields",
          "FieldLengths",
          "Resolution"],
        "Length":26,
        "Fields":[
          {
            "Order":1,
            "Id":"prn",
            "Name":"PRN",
            "BitLength":8,
            "BitOffset":0,
            "BitStart":0,
            "Type":"Integer",
            "Resolution":1,
            "Signed":false,
            "RangeMin":0,
            "RangeMax":253},
          {
            "Order":2,
            "Id":"gpsWeekNumber",
            "Name":"GPS Week number",
            "BitLength":16,
            "BitOffset":8,
            "BitStart":0,
            "Type":"Integer",
            "Resolution":1,
            "Signed":false,
            "RangeMin":0,
            "RangeMax":65533},
          {
            "Order":3,
            "Id":"svHealthBits",
            "Name":"SV Health Bits",
            "BitLength":8,
            "BitOffset":24,
            "BitStart":0,
            "Type":"Binary data",
            "Resolution":1,
            "Signed":false},
          {
            "Order":4,
            "Id":"eccentricity",
            "Name":"Eccentricity",
            "Description":"'e' in table 20-VI in ICD-GPS-200",
            "BitLength":16,
            "BitOffset":32,
            "BitStart":0,
            "Units":"m/m",
            "Type":"Number",
            "Resolution":4.76837e-07,
            "Signed":false,
            "RangeMin":0,
            "RangeMax":0.03124856948852539},
          {
            "Order":5,
            "Id":"almanacReferenceTime",
            "Name":"Almanac Reference Time",
            "Description":"'t~oa~' in table 20-VI in ICD-GPS-200",
            "BitLength":8,
            "BitOffset":48,
            "BitStart":0,
            "Units":"s",
            "Type":"Number",
            "Resolution":4096,
            "Signed":false,
            "RangeMin":0,
            "RangeMax":1036288},
          {
            "Order":6,
            "Id":"inclinationAngle",
            "Name":"Inclination Angle",
            "Description":"'δ~i~' in table 20-VI in ICD-GPS-200",
            "BitLength":16,
            "BitOffset":56,
            "BitStart":0,
            "Units":"semi-circle",
            "Type":"Number",
            "Resolution":1.90735e-06,
            "Signed":true,
            "RangeMin":-0.06249809265136719,
            "RangeMax":0.06249427795410156},
          {
            "Order":7,
            "Id":"rateOfRightAscension",
            "Name":"Rate of Right Ascension",
            "Description":"'̇Ω' in table 20-VI in ICD-GPS-200",
            "BitLength":16,
            "BitOffset":72,
            "BitStart":0,
            "Units":"semi-circle/s",
            "Type":"Number",
            "Resolution":3.63798e-12,
            "Signed":true,
            "RangeMin":-1.192056515719742e-07,
            "RangeMax":1.1919837561436e-07},
          {
            "Order":8,
            "Id":"rootOfSemiMajorAxis",
            "Name":"Root of Semi-major Axis",
            "Description":"'√ a' in table 20-VI in ICD-GPS-200",
            "BitLength":24,
            "BitOffset":88,
            "BitStart":0,
            "Units":"sqrt(m)",
            "Type":"Number",
            "Resolution":0.000488281,
            "Signed":false,
            "RangeMin":0,
            "RangeMax":8191.99853515625},
          {
            "Order":9,
            "Id":"argumentOfPerigee",
            "Name":"Argument of Perigee",
            "Description":"'Ω~0~' in table 20-VI in ICD-GPS-200",
            "BitLength":24,
            "BitOffset":112,
            "BitStart":0,
            "Units":"semi-circle",
            "Type":"Number",
            "Resolution":1.19209e-07,
            "Signed":true,
            "RangeMin":-0.9999998807907104,
            "RangeMax":0.9999996423721313},
          {
            "Order":10,
            "Id":"longitudeOfAscensionNode",
            "Name":"Longitude of Ascension Node",
            "Description":"'ω' in table 20-VI in ICD-GPS-200",
            "BitLength":24,
            "BitOffset":136,
            "BitStart":0,
            "Units":"semi-circle",
            "Type":"Number",
            "Resolution":1.19209e-07,
            "Signed":true,
            "RangeMin":-0.9999998807907104,
            "RangeMax":0.9999996423721313},
          {
            "Order":11,
            "Id":"meanAnomaly",
            "Name":"Mean Anomaly",
            "Description":"'M~0~' in table 20-VI in ICD-GPS-200",
            "BitLength":24,
            "BitOffset":160,
            "BitStart":0,
            "Units":"semi-circle",
            "Type":"Number",
            "Resolution":1.19209e-07,
            "Signed":true,
            "RangeMin":-0.9999998807907104,
            "RangeMax":0.9999996423721313},
          {
            "Order":12,
            "Id":"clockParameter1",
            "Name":"Clock Parameter 1",
            "Description":"'a~f0~' in table 20-VI in ICD-GPS-200",
            "BitLength":11,
            "BitOffset":184,
            "BitStart":0,
            "Units":"s",
            "Type":"Number",
            "Resolution":9.53674e-07,
            "Signed":true,
            "RangeMin":-0.0009756088256835938,
            "RangeMax":0.0009737014770507812},
          {
            "Order":13,
            "Id":"clockParameter2",
            "Name":"Clock Parameter 2",
            "Description":"'a~f1~' in table 20-VI in ICD-GPS-200",
            "BitLength":11,
            "BitOffset":195,
            "BitStart":3,
            "Units":"s/s",
            "Type":"Number",
            "Resolution":3.63798e-12,
            "Signed":true,
            "RangeMin":-3.721652319654822e-09,
            "RangeMax":3.714376362040639e-09},
          {
            "Order":14,
            "Id":"reserved",
            "Name":"Reserved",
            "BitLength":2,
            "BitOffset":206,
            "BitStart":6,
            "Resolution":1,
            "Signed":false
			}
		]
	};