= NMEA2000 descriptor for PGN 129541 GPS Almanac Data

This descriptor for NMEA2000 PGN 129541 includes greek characters that the JavaScript engine on Windows cannot handle.
It has, therefore been omitted from the built-in library of descriptors.

If you are not running on windows, you can use this as a custom descriptor

https://github.com/antipole2/JavaScripts-shared/blob/main/descriptor129541
/descriptor129541.js[descriptor129541.js]

It is an alternative to the ShipDriver plugin but does not use steering to gradually change course.

It generates GLL, VTG and WML NMEA sentences.  You could add others as required.

You can set Speed Over Ground (SOG), Course Over Ground (COG), Wind angle and wind speed.

Selecting *Compass course* will then drive the boat along the selected course.  The angle to the wind is displayed.
Alternatively, you can instead specify an angle to the wind and select *Port tack* or *Starboard tack*.  It will then calculate the required COG.
Selecting the opposite tack will tack the boat.

After changing the parameters, you need to click on one of the buttons to put the chnages into effect. 

TIP: Driver can be run in its own console and used, for example, to experiment with or test the TackAdvisor and SendActiveRoute scripts running in their own consoles.
