= SendActiveRoute

https://github.com/antipole2/JavaScripts-shared/blob/main/SendActiveRoute/SendActiveRoute.js[SendActiveRoute.js]

== What this script addresses

Running a tablet or phone as a repeater for OpenCPN is unsatisfactory.
Viewing OpenCPN on such a small screen gives a poor experience.
Further, if OpenCPN were to fail, the repeater will also fail.
There is no resilience.

There are navigational applications better optimised these devices and more robust.
I use https://inavx.com[iNavX], which is available on iOS (iPad and iPhone) and Android devices.
I will asume the other device is running iNavX here.

If OpenCPN is being used as the main planning tool and navigational application,
iNavX needs to shadow OpenCPN and keep synchronised with any changes in the navigation.

This script causes iNavX to shadow OpenCPN by adopting any active waypoint or route.
As you advance along the route, iNavX will also advance.
If you amend the route by adding or moving routepoints, iNavX will update accordingly.

In the event that OpenCPN were to fail, iNavX will continue to navigate from its own ship's navigational feed.
If that feed were to fail, a device with its own GPS receiver will switch to using that.
This provided important resilience.

== What the script does

The script monitors for when you have an active waypoint  or route.

When the script detects an active route, it sends the following NMEA sentences:

. A series of WPL sentences defining the routepoints in the route
. A group of RTE sentences creating a route comprising the routepoints
. A BOD sentence with the bearing from the position at which the leg was activated to the next routepoint.
. A repeat of the WPL sentence for the active routepoint

These sentences cause iNavX to hold a mirror copy of the current route and navigate to the active point within the route.

While a route is active, OpenCPN sends APB sentences with the routeName.
Unfortunately, that route name is truncated.
This script fixes up the APB sentences to carry the full route name.

== Instructions for making this work

For this to work, your device running iNavX needs to receive NMEA data over a WiFi connection via a WiFi router.

Note that many instrument WiFi gateways create their own WiFi network and are not actual routers.
This is the case, for example, for the Actisense W2K-1 and also the Yacht Devices YDNR-02N.

If your gateway is not also a router, you need a WiFi router and need to connect your gateway as a client of that network.
You could use a 12V-powered WiFI router (readily available) or your computer may be able to provide this.
MacOS can create an _ad hoc_ WiFi network from the WiFi pull-down menu - in Monterey and later, this is hidden unless you enable it in Settings->Network->WiFi->Advanced and tick _Show legacy networks and options_.

. Have OpenCPN receive NMEA data from your gateway on one port - say 60001
. Have OpenCPN send NMEA data on a different port - say 60002 +
Drop outgoing sentences ECRMB,ECAPB because the script sends modified sentences NVRMB,NVAPB
. Connect your device to the same WiFi network
. Within iNavX select Instruments  > TCP/IP and set the protocol and port number to as in Step 2 above.
. On the same panel, enable Waypoints and enable Link. +
You should now see the NMEA sentences scrolling in the monitoring pane of this panel.
. Click Done and then select the Chart.

The device should now follow the ship's navigation using the ship's navigation data.

When a waypoint becomes active in OpenCPN, it becomes active in iNavX.

When a route is activated in OpenCPN, it appears as the active route in iNavX.
As OpenCPN advances the routepoint, so iNavX advances its active routepoint.
Progress along the route is available in the route tab of the ribbon at the top of the iNavX screen,
together with predicted time on route and ETA.

If you wish to force an advance to the next routepoint, this should be done on OpenCPN, whereupon iNavX will update too.

If you advance the routepoint in iNavX, it will start ignoring changes in the active routepoint send from OpenCPN.
To restore this, go to the panel used for step 5 above, turn Enable Waypoints off and back on again.

== Limitations
[WARNING]
====
*Duplication of names* +
Unlike OpenCPN but like most navigationl applications, iNavX identifies waypoints and routes by their unique name.
It replaces anything with the same name, so if I navigate +
Route 1 with routepoints A, B, C & D +
and then a different +
Route 2 with routepoints A, X, C & Y +
Route 1 still exists withing iNavX but the routepoints A and C within it have the position of those routepoints in Route B.
====

CAUTION: To avoid refetching the whole list of routes every few sconds, the script does not check for a change in route name.
So if you edit the route name in OpenCPN, the script will get confused.
Stop the script and start it again.

== My network set up

On Antipole I have an NMEA2000 network and an Actisense W2K-1 NMEA2000 to WiFi converter.
The W2K-1 is usually used to create a WiFi network.
However, it is not a router and you cannot use it to connect OpenCPN and other devices.

I happen to have a USB-powered mini-hub that British Telecom gave me when we were moving house.
This does contain a router.
So I connect the W2K-1 in client mode to the minihub and use this to provide the WiFi network.
OpenCPN receives the NMEA data from the W2K-1 on port 60001
and sends NMEA data on port 60002.
Other devices receive via port 60002.

In the event that OpenCPN were to fail, I would connect the iOS devices via port 60001 and they would receive the navigational data directly, without it being procesed via OpenCPN.

== Implementation notes

These notes may be of iterest to those maintining the script.
They are not need to use it.

=== Forming the RTE sentences

A challenge in writing this script was forming the RTE sentences, which list the routepoints.
NMEA sentences are limited to 80 characters, so several "n of m" installments are required.
How many depends on the number of routepoints and the length of the routepoint names.

The easy way out would be to send each routepoint in its own RTE installment.
So with 6 routepoints there would be 6 RTE installments.
Simpe but inefficient.

The script actually packs the routepoints into the minimum number of RTE installements possible.
